### ISSUE TITLE
"response":"error","error":"Tag (file name) does not exist: Default"

### ISSUE THREAD

**Issue by xdmx** [onesky/i18n-one_sky-ruby#8]
I've installed the last version of the gem on a rails 4 project, set the tokens, project name and platform id, but when I do rake one_sky:download the response is the following:

```
** Invoke one_sky:download (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute one_sky:download
Downloading translations for I18n Simple Backend:
rake aborted!
{"response":"error","error":"Tag (file name) does not exist: Default"}
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/client.rb:76:in `parse_response'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/client.rb:64:in `fetch_response'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/client.rb:25:in `get'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/translation.rb:100:in `get'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/translation.rb:96:in `download_file'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/one_sky-2.0.1/lib/one_sky/translation.rb:71:in `download_yaml'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/simple_client.rb:24:in `block in download'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/simple_client.rb:15:in `each'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/simple_client.rb:15:in `download'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/gems/i18n-one_sky-2.0.10/lib/i18n/one_sky/rails/tasks/i18n-one_sky.rake:11:in `block (2 levels) in <top (required)>'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/bin/ruby_noexec_wrapper:14:in `eval'
/home/user/.rvm/gems/ruby-2.0.0-p247@project/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => one_sky:download
(See full trace by running task with --trace)
```

**Comment by kwunlokng** [comment]
Hi there,

There is a constraint of our gem to use "Default" as the name of file. You may either upload the strings with our gem or update the file name you uploaded on OneSky platform into "Default".

We'll schedule a new Ruby Gem to tackle this issue. Thanks for reporting.

Best,
Loki

**Comment by xdmx** [comment]
Hi Loki, how is it supposed to work with the github tracking then? I wish all our english (main) locales to be automatically tracked on OneSky, and then fetch automatically all the translations automatically when deploying/commit, so there is 0 effort to keep all the translations updated. We also like to separate files based on the context (models.yml, views.yml, etc) in a "locales/en" folder, at least for the main language, for the translations we don't care if they're a single file

Do you have any idea when the new gem will be available?

**Comment by giedriusr** [comment]
Apparently this hasn't been fixed yet, a? I have the same issue.

**Comment by sluceno** [comment]
Hey, I have the same issue here. Is this gonna be fixed soon?

Thanks.

**Comment by VLMH** [comment]
@xdmx @giedriusr @sluceno FYI, the long due [new Rails gem](https://rubygems.org/gems/onesky-rails) is finally here. As this old gem is based on strings to work with OneSky platform, by nature there is the problem of not being able to separate strings into files as context. The new gem is based on file so doesn't have this problem.

In addition, now you can deprecate strings that are no longer in use (removed from string file) by changing settings in config file. Hope the new gem can solve the issues you've encountered. I will be actively maintaining the gem to make it work smoothly for you.

Again, sorry for the wait!

**Comment by giedriusr** [comment]
:+1:
